import { writeFileSync, mkdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import type { AiDocBlock, KnowledgeBase, ScanResult } from '../types'
import { readEnrichedGraph, GRAPH_FILENAME } from '../graph/serializer'

// ─── Knowledge base ────────────────────────────────────────────────────────

export function writeKnowledgeBase(result: ScanResult, projectRoot: string): void {
  const outDir = join(projectRoot, '.codemod')
  mkdirSync(outDir, { recursive: true })
  const kb = buildKnowledgeBase(result.docs)
  writeFileSync(join(outDir, 'ai-knowledge-base.json'), JSON.stringify(kb, null, 2), 'utf-8')
}

// ─── AGENTS.md ─────────────────────────────────────────────────────────────

export const AGENTS_GENERATED_START = '<!-- aidoc-kit:generated:start — do not edit inside this block, it is rewritten by aidoc-kit -->'
export const AGENTS_GENERATED_END = '<!-- aidoc-kit:generated:end -->'

/**
 * Merge the generated block into an existing AGENTS.md without destroying
 * hand-written content:
 * - no existing file, or a fully generated legacy file → generated block alone
 * - existing markers → only the content between them is replaced
 * - hand-written file without markers → preserved as is, block appended
 */
export function mergeAgentsMd(existing: string | null, generatedBlock: string): string {
  if (existing === null) return generatedBlock + '\n'

  const start = existing.indexOf(AGENTS_GENERATED_START)
  const end = existing.indexOf(AGENTS_GENERATED_END)
  if (start !== -1 && end > start) {
    return existing.slice(0, start) + generatedBlock + existing.slice(end + AGENTS_GENERATED_END.length)
  }

  // Legacy file entirely produced by aidoc-kit < 1.3.3 (no markers yet)
  if (/^# AGENTS\s*\n+> Generated by aidoc-kit/.test(existing)) return generatedBlock + '\n'

  return existing.trimEnd() + '\n\n' + generatedBlock + '\n'
}

export function writeAgentsMd(result: ScanResult, projectRoot: string): void {
  const kb = buildKnowledgeBase(result.docs)
  const lines: string[] = [
    AGENTS_GENERATED_START,
    '# AGENTS',
    '',
    `> Generated by aidoc-kit on ${new Date().toISOString().slice(0, 10)}`,
    `> ${result.totalScanned} files scanned — ${result.docs.length} with @ai-* docs`,
    '',
  ]

  // Enriched code graph section — placed first so agents see it before
  // anything else. Only written when aidoc-graph.json exists.
  const graph = readEnrichedGraph(projectRoot)
  if (graph) {
    lines.push(
      `## Code graph — query it, never read it in full`,
      '',
      `\`${GRAPH_FILENAME}\` (project root) maps every file: role (client/server/universal),`,
      `criticality 0-100, dependents and dependencies. Generated ${graph.generatedAt.slice(0, 10)}`,
      `by \`npx aidoc-kit index\` — ${graph.stats.files} files, ${graph.stats.edges} edges.`,
      '',
      `Rules for AI agents:`,
      '',
      `1. **Never load ${GRAPH_FILENAME} entirely** — it grows with the project. Query it.`,
      `2. Before modifying a file, check its entry. If \`criticalityLevel\` is \`high\` or`,
      `   \`critical\`, read every dependent file first.`,
      `3. Never import a \`role: server\` file from client code.`,
      `4. Freshness: if \`generatedAt\` is older than the last commit, the graph may be stale —`,
      `   ask the developer to run \`npx aidoc-kit index --incremental\` (do not run it yourself).`,
      '',
      `Queries (replace the path):`,
      '',
      '```bash',
      `# One file's entry (role, criticality, tags)`,
      `node -e "const g=require('./${GRAPH_FILENAME}');console.log(g.files.find(f=>f.file==='src/foo.ts'))"`,
      '',
      `# Who depends on a file (check these before modifying it)`,
      `node -e "const g=require('./${GRAPH_FILENAME}');console.log([...new Set(g.edges.filter(e=>e.to==='src/foo.ts').map(e=>e.from))])"`,
      '',
      `# Most critical files`,
      `node -e "const g=require('./${GRAPH_FILENAME}');g.files.filter(f=>f.criticality>=55).forEach(f=>console.log(f.criticality,f.file))"`,
      '```',
      '',
    )
  }

  lines.push(
    '## Agents and their domains',
    '',
  )

  for (const [agent, info] of Object.entries(kb.agents)) {
    lines.push(`### ${agent}`, '')
    lines.push(`**Files:** ${info.owns.length}`)
    info.owns.slice(0, 10).forEach(f => lines.push(`- \`${f}\``))
    if (info.owns.length > 10) lines.push(`- *(+ ${info.owns.length - 10} more)*`)
    if (info.consultedBy.length > 0) {
      lines.push('', `**Consulted by:** ${info.consultedBy.join(', ')}`)
    }
    lines.push('')
  }

  if (Object.keys(kb.runtimeMap).length > 0) {
    lines.push('## Runtime Map', '')
    for (const [runtime, files] of Object.entries(kb.runtimeMap)) {
      lines.push(`### ${runtime} (${files.length} files)`, '')
      files.slice(0, 5).forEach(f => lines.push(`- \`${f}\``))
      if (files.length > 5) lines.push(`- *(+ ${files.length - 5} more)*`)
      lines.push('')
    }
  }

  if (result.filesWithoutDocs.length > 0) {
    lines.push(
      '## Files without @ai-* documentation',
      '',
      `${result.filesWithoutDocs.length} file(s) without \`@ai-*\` block detected.`,
      'The developer can generate the missing blocks with:',
      '',
      '```bash',
      'npx aidoc-kit scan --write --yes',
      '```',
      '',
      '> **Note for AI agents**: do not run this command yourself.',
      '> Report it to the developer if you notice undocumented files.',
      '',
    )
  }

  lines.push(
    '## Large files — read the chunk before modifying',
    '',
    'Files over 150 lines have a structured summary in `.codemod/chunks/`.',
    'Before modifying a large file, **read the corresponding `.md` file** in that folder.',
    'Do not try to read the source file in full — use the chunk.',
    '',
    'Example: before modifying `src/contexts/auth-context.tsx`',
    '=> Read `.codemod/chunks/src/contexts/auth-context.tsx.md`',
    '',
    '> Chunks are generated and maintained by the developer via `npx aidoc-kit chunk`.',
    '> If a chunk is missing, ask the developer to run this command.',
    '> **Note for AI agents**: aidoc-kit must be installed as a dev dep (`npm install -D aidoc-kit`).',
    '> All aidoc-kit commands should be delegated to the developer, not run directly.',
    '',
  )

  lines.push(AGENTS_GENERATED_END)

  const path = join(projectRoot, 'AGENTS.md')
  let existing: string | null = null
  try {
    existing = readFileSync(path, 'utf-8')
  } catch {
    // no existing file
  }
  writeFileSync(path, mergeAgentsMd(existing, lines.join('\n')), 'utf-8')
}

// ─── Prepend doc block to a file ──────────────────────────────────────────

export function writeDocBlock(filePath: string, docBlock: string): void {
  const existing = readFileSync(filePath, 'utf-8')
  // Check for a real generated block (JSDoc line " * @ai-agent …"), not just
  // the string "@ai-agent" appearing in source code (e.g. scanner internals).
  if (existing.includes(' * @ai-agent ')) return // already documented

  // Preserve shebang line at the very top (e.g. #!/usr/bin/env node in cli.ts)
  if (existing.startsWith('#!')) {
    const newlineIdx = existing.indexOf('\n')
    const shebang = existing.slice(0, newlineIdx + 1)
    const rest = existing.slice(newlineIdx + 1)
    writeFileSync(filePath, shebang + docBlock + '\n' + rest, 'utf-8')
  } else {
    writeFileSync(filePath, docBlock + '\n' + existing, 'utf-8')
  }
}

// ─── Builder ────────────────────────────────────────────────────────────────

function buildKnowledgeBase(docs: AiDocBlock[]): KnowledgeBase {
  const agents: KnowledgeBase['agents'] = {}
  const cascadeGraph: Record<string, string[]> = {}
  const runtimeMap: Record<string, string[]> = {}
  const validationCommands: Record<string, string[]> = {}

  for (const doc of docs) {
    // Agent ownership
    if (!agents[doc.agent]) agents[doc.agent] = { owns: [], consultedBy: [] }
    agents[doc.agent].owns.push(doc.file)

    // Related agents get a "consultedBy" entry
    for (const rel of doc.related) {
      if (!rel) continue
      if (!agents[rel]) agents[rel] = { owns: [], consultedBy: [] }
      if (!agents[rel].consultedBy.includes(doc.agent)) {
        agents[rel].consultedBy.push(doc.agent)
      }
    }

    // Cascade graph
    if (doc.cascade.length > 0) cascadeGraph[doc.file] = doc.cascade

    // Runtime map
    const rt = doc.runtime || 'UNIVERSEL'
    if (!runtimeMap[rt]) runtimeMap[rt] = []
    runtimeMap[rt].push(doc.file)

    // Validation commands
    if (doc.validate) {
      if (!validationCommands[doc.validate]) validationCommands[doc.validate] = []
      validationCommands[doc.validate].push(doc.file)
    }
  }

  return { generatedAt: new Date().toISOString(), agents, cascadeGraph, runtimeMap, validationCommands }
}
