import { writeFileSync, mkdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import type { AiDocBlock, KnowledgeBase, ScanResult } from '../types'

// ─── Knowledge base ────────────────────────────────────────────────────────

export function writeKnowledgeBase(result: ScanResult, projectRoot: string): void {
  const outDir = join(projectRoot, '.codemod')
  mkdirSync(outDir, { recursive: true })
  const kb = buildKnowledgeBase(result.docs)
  writeFileSync(join(outDir, 'ai-knowledge-base.json'), JSON.stringify(kb, null, 2), 'utf-8')
}

// ─── AGENTS.md ─────────────────────────────────────────────────────────────

export function writeAgentsMd(result: ScanResult, projectRoot: string): void {
  const kb = buildKnowledgeBase(result.docs)
  const lines: string[] = [
    '# AGENTS',
    '',
    `> Generated by aidoc-kit on ${new Date().toISOString().slice(0, 10)}`,
    `> ${result.totalScanned} files scanned — ${result.docs.length} with @ai-* docs`,
    '',
    '## Agents and their domains',
    '',
  ]

  for (const [agent, info] of Object.entries(kb.agents)) {
    lines.push(`### ${agent}`, '')
    lines.push(`**Files:** ${info.owns.length}`)
    info.owns.slice(0, 10).forEach(f => lines.push(`- \`${f}\``))
    if (info.owns.length > 10) lines.push(`- *(+ ${info.owns.length - 10} more)*`)
    if (info.consultedBy.length > 0) {
      lines.push('', `**Consulted by:** ${info.consultedBy.join(', ')}`)
    }
    lines.push('')
  }

  if (Object.keys(kb.runtimeMap).length > 0) {
    lines.push('## Runtime Map', '')
    for (const [runtime, files] of Object.entries(kb.runtimeMap)) {
      lines.push(`### ${runtime} (${files.length} files)`, '')
      files.slice(0, 5).forEach(f => lines.push(`- \`${f}\``))
      if (files.length > 5) lines.push(`- *(+ ${files.length - 5} more)*`)
      lines.push('')
    }
  }

  if (result.filesWithoutDocs.length > 0) {
    lines.push(
      '## Files without @ai-* documentation',
      '',
      `${result.filesWithoutDocs.length} file(s) without \`@ai-*\` block detected.`,
      'The developer can generate the missing blocks with:',
      '',
      '```bash',
      'npx aidoc-kit scan --write --yes',
      '```',
      '',
      '> **Note for AI agents**: do not run this command yourself.',
      '> Report it to the developer if you notice undocumented files.',
      '',
    )
  }

  lines.push(
    '## Large files — read the chunk before modifying',
    '',
    'Files over 150 lines have a structured summary in `.codemod/chunks/`.',
    'Before modifying a large file, **read the corresponding `.md` file** in that folder.',
    'Do not try to read the source file in full — use the chunk.',
    '',
    'Example: before modifying `src/contexts/auth-context.tsx`',
    '=> Read `.codemod/chunks/src/contexts/auth-context.tsx.md`',
    '',
    '> Chunks are generated and maintained by the developer via `npx aidoc-kit chunk`.',
    '> If a chunk is missing, ask the developer to run this command.',
    '> **Note for AI agents**: aidoc-kit must be installed as a dev dep (`npm install -D aidoc-kit`).',
    '> All aidoc-kit commands should be delegated to the developer, not run directly.',
    '',
  )

  writeFileSync(join(projectRoot, 'AGENTS.md'), lines.join('\n'), 'utf-8')
}

// ─── Prepend doc block to a file ──────────────────────────────────────────

export function writeDocBlock(filePath: string, docBlock: string): void {
  const existing = readFileSync(filePath, 'utf-8')
  // Check for a real generated block (JSDoc line " * @ai-agent …"), not just
  // the string "@ai-agent" appearing in source code (e.g. scanner internals).
  if (existing.includes(' * @ai-agent ')) return // already documented

  // Preserve shebang line at the very top (e.g. #!/usr/bin/env node in cli.ts)
  if (existing.startsWith('#!')) {
    const newlineIdx = existing.indexOf('\n')
    const shebang = existing.slice(0, newlineIdx + 1)
    const rest = existing.slice(newlineIdx + 1)
    writeFileSync(filePath, shebang + docBlock + '\n' + rest, 'utf-8')
  } else {
    writeFileSync(filePath, docBlock + '\n' + existing, 'utf-8')
  }
}

// ─── Builder ────────────────────────────────────────────────────────────────

function buildKnowledgeBase(docs: AiDocBlock[]): KnowledgeBase {
  const agents: KnowledgeBase['agents'] = {}
  const cascadeGraph: Record<string, string[]> = {}
  const runtimeMap: Record<string, string[]> = {}
  const validationCommands: Record<string, string[]> = {}

  for (const doc of docs) {
    // Agent ownership
    if (!agents[doc.agent]) agents[doc.agent] = { owns: [], consultedBy: [] }
    agents[doc.agent].owns.push(doc.file)

    // Related agents get a "consultedBy" entry
    for (const rel of doc.related) {
      if (!rel) continue
      if (!agents[rel]) agents[rel] = { owns: [], consultedBy: [] }
      if (!agents[rel].consultedBy.includes(doc.agent)) {
        agents[rel].consultedBy.push(doc.agent)
      }
    }

    // Cascade graph
    if (doc.cascade.length > 0) cascadeGraph[doc.file] = doc.cascade

    // Runtime map
    const rt = doc.runtime || 'UNIVERSEL'
    if (!runtimeMap[rt]) runtimeMap[rt] = []
    runtimeMap[rt].push(doc.file)

    // Validation commands
    if (doc.validate) {
      if (!validationCommands[doc.validate]) validationCommands[doc.validate] = []
      validationCommands[doc.validate].push(doc.file)
    }
  }

  return { generatedAt: new Date().toISOString(), agents, cascadeGraph, runtimeMap, validationCommands }
}
