import { test } from 'node:test'
import assert from 'node:assert/strict'
import { mkdtempSync, mkdirSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { mergeAgentsMd, buildAgentsMdBlock, AGENTS_GENERATED_START, AGENTS_GENERATED_END } from './writer'
import type { AiDocBlock, ScanResult } from '../types'

function withTempProject(fn: (root: string) => void): void {
  const root = mkdtempSync(join(tmpdir(), 'aidoc-writer-'))
  try { fn(root) } finally { rmSync(root, { recursive: true, force: true }) }
}

const docBlock: AiDocBlock = {
  file: 'src/a.ts', agent: 'general-expert', related: [], runtime: 'UNIVERSEL', context: '',
  whenModifying: [], cascade: [], validate: 'npm run typecheck', neverDo: [], patterns: [],
}

test('buildAgentsMdBlock: graph-only project gets no @ai-* or chunk instructions', () => {
  withTempProject(root => {
    const result: ScanResult = { docs: [], filesWithoutDocs: ['src/a.ts', 'src/b.ts'], totalScanned: 2 }
    const block = buildAgentsMdBlock(result, root)
    assert.ok(!block.includes('scan --write'))
    assert.ok(!block.includes('.codemod/chunks'))
    assert.ok(!block.includes('## Agents and their domains'))
  })
})

test('buildAgentsMdBlock: sections appear when the project actually uses them', () => {
  withTempProject(root => {
    mkdirSync(join(root, '.codemod', 'chunks'), { recursive: true })
    const result: ScanResult = { docs: [docBlock], filesWithoutDocs: ['src/b.ts'], totalScanned: 2 }
    const block = buildAgentsMdBlock(result, root)
    assert.ok(block.includes('scan --write'))
    assert.ok(block.includes('.codemod/chunks'))
    assert.ok(block.includes('## Agents and their domains'))
  })
})

const block = `${AGENTS_GENERATED_START}\n# AGENTS\n\n> Generated by aidoc-kit on 2026-09-15\ncontent v2\n${AGENTS_GENERATED_END}`

test('mergeAgentsMd: no existing file → generated block alone', () => {
  assert.equal(mergeAgentsMd(null, block), block + '\n')
})

test('mergeAgentsMd: hand-written file is preserved, block appended', () => {
  const manual = '# Mes règles projet\n\nNe jamais toucher à la CSP sans validation.\n'
  const merged = mergeAgentsMd(manual, block)
  assert.ok(merged.startsWith('# Mes règles projet'))
  assert.ok(merged.includes('Ne jamais toucher à la CSP'))
  assert.ok(merged.includes('content v2'))
})

test('mergeAgentsMd: only the marked block is replaced on re-run', () => {
  const manual = '# Mes règles projet\n\nRègle manuelle.\n'
  const v1 = mergeAgentsMd(manual, block)
  const blockV3 = block.replace('content v2', 'content v3')
  const v2 = mergeAgentsMd(v1, blockV3)
  assert.ok(v2.includes('Règle manuelle.'))
  assert.ok(v2.includes('content v3'))
  assert.ok(!v2.includes('content v2'))
  // idempotent: a third run with the same block changes nothing
  assert.equal(mergeAgentsMd(v2, blockV3), v2)
})

test('mergeAgentsMd: legacy fully generated file is replaced, not duplicated', () => {
  const legacy = '# AGENTS\n\n> Generated by aidoc-kit on 2026-09-10\nold content\n'
  const merged = mergeAgentsMd(legacy, block)
  assert.equal(merged, block + '\n')
  assert.ok(!merged.includes('old content'))
})

test('mergeAgentsMd: manual content after the block survives re-runs', () => {
  const withTrailer = block + '\n\n## Notes ajoutées à la main\nGarder ceci.\n'
  const merged = mergeAgentsMd(withTrailer, block.replace('content v2', 'content v3'))
  assert.ok(merged.includes('Garder ceci.'))
  assert.ok(merged.includes('content v3'))
})
